# Generated by Django 5.0.6 on 2024-05-12 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('fec_nac', models.DateField()),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=16)),
                ('dni', models.IntegerField()),
                ('tel', models.CharField(max_length=15)),
                ('id_rol', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Usuario de MisRutinas',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
    ]
