# Generated by Django 5.0.6 on 2024-05-12 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago de clase', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='id_user_clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clases.usuarioclase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
